"""Provenance-specific grounding and consistency rules."""

import re

from build_etrue import canonical_video_key, normalize_date
from utils.evidence import add_field_evidence
from utils.text import containment_overlap


PROVENANCE_STATUSES = {
    "original",
    "earlier version found",
    "repost",
    "edited excerpt",
    "compilation",
    "screen recording",
    "unknown",
}


def previous_context_is_useful(value, claimed_framing, grounding_text):
    summary = re.sub(r"\s+", " ", str(value or "").strip())
    lowered = summary.lower()
    boilerplate = (
        "previous context summary",
        "not provided",
        "not relevant",
        "does not match",
        "provided information",
    )
    if len(summary) < 25 or any(phrase in lowered for phrase in boilerplate):
        return False
    if containment_overlap(summary, claimed_framing) >= 0.65:
        return False

    context_cue = re.search(
        r"\b(actually|originally|previously|filmed|recorded|depicts|footage|newsreel|archive)\b",
        lowered,
    )
    if not context_cue:
        return False

    summary_words = set(re.findall(r"[a-z0-9]+", lowered))
    evidence_words = set(re.findall(r"[a-z0-9]+", str(grounding_text or "").lower()))
    return bool(summary_words) and len(summary_words & evidence_words) / len(summary_words) >= 0.7


def apply_provenance_rules(verification):
    provenance = verification["provenance"]
    previous_context = provenance.get("previous_context_summary")
    claimed_framing = verification["motivation"].get("claimed_framing")

    if not previous_context or previous_context == claimed_framing:
        provenance["previous_context_summary"] = None
        provenance["provenance_mismatch"] = None

    if provenance.get("provenance_status") not in PROVENANCE_STATUSES:
        provenance["provenance_status"] = "unknown"


def _candidate_date(value):
    """Return the earliest normalized date exposed by a search candidate."""
    dates = [
        normalize_date(value.get(key))
        for key in ("published_at", "archive_first_seen", "date")
    ]
    dates = [date for date in dates if date]
    return min(dates) if dates else None


def _candidate_url(value):
    return value.get("canonical_url") or value.get("final_url") or value.get("url")


def _url_key(value):
    if not value:
        return None
    key = canonical_video_key(value, "")
    return str(value).rstrip("/").casefold() if key == "claim:" else key


def _same_url(left, right):
    return bool(left and right and _url_key(left) == _url_key(right))


def _exact_search_phrase_is_present(item):
    if item.get("query_type") not in {"transcript", "caption"}:
        return False
    phrase = " ".join(str(item.get("query") or "").strip('"').casefold().split())
    haystack = " ".join(
        str(item.get(key) or "")
        for key in ("title", "description", "context_excerpt")
    )
    haystack = " ".join(haystack.casefold().split())
    return bool(phrase and phrase in haystack)


def apply_search_provenance(
    extra,
    image_search,
    evidence_by_url=None,
    text_results=(),
):
    """Merge confirmed phrase and reverse-image candidates into provenance.

    Google Web Detection pages are visual-match candidates.  Search-engine text
    results qualify only when a distinctive quoted transcript/caption phrase is
    present verbatim on the result page.
    """
    evidence_by_url = evidence_by_url or {}
    verification = extra["verification"]
    provenance = verification["provenance"]
    pages = (image_search or {}).get("pages") or []

    # Keep confirmed local matches and replace only the reverse-image candidates
    # generated by a previous search run.
    generated_sources = {"reverse_image", "transcript_search", "caption_search"}
    matches = [
        match
        for match in provenance.get("near_duplicate_matches") or []
        if match.get("source") not in generated_sources
    ]
    page_by_url = {}
    match_evidence = []
    for page in pages:
        url = _candidate_url(page)
        if not url:
            continue
        match_types = list(page.get("match_types") or [])
        if not set(match_types) & {"full", "partial"}:
            continue
        match = {
            "url": url,
            "date": _candidate_date(page),
            "source": "reverse_image",
            "match_types": match_types,
            "matched_frames": list(page.get("matched_frames") or []),
            "match_count": page.get("match_count")
            or len(page.get("matched_frames") or []),
        }
        matches.append({key: value for key, value in match.items() if value is not None})
        page_by_url[url] = page
        evidence_id = evidence_by_url.get(page.get("url")) or evidence_by_url.get(url)
        if evidence_id:
            match_evidence.append(evidence_id)

    for item in text_results or []:
        if not _exact_search_phrase_is_present(item):
            continue
        url = _candidate_url(item)
        if not url:
            continue
        query_type = item["query_type"]
        match = {
            "url": url,
            "date": _candidate_date(item),
            "source": query_type + "_search",
            "match_types": ["exact " + query_type + " phrase"],
            "query": item.get("query"),
        }
        matches.append({key: value for key, value in match.items() if value is not None})
        page_by_url[url] = item
        evidence_id = evidence_by_url.get(item.get("url")) or evidence_by_url.get(url)
        if evidence_id:
            match_evidence.append(evidence_id)

    # Stable de-duplication matters when a canonical URL differs from the URL
    # returned by Web Detection.
    merged = {}
    for match in matches:
        key = _url_key(match.get("url")) or match.get("claim_id")
        if key not in merged or (
            match.get("source") not in generated_sources
            and merged[key].get("source") in generated_sources
        ):
            merged[key] = match
    matches = list(merged.values())
    matches.sort(key=lambda item: (item.get("date") is None, item.get("date") or "", item.get("url") or ""))
    provenance["near_duplicate_matches"] = matches
    if match_evidence:
        add_field_evidence(
            extra,
            "verification.provenance.near_duplicate_matches",
            match_evidence,
        )

    current_url = extra.get("normalized_video_information", {}).get("video_url")
    upload_date = normalize_date(verification["date"].get("video_upload_date"))
    current = {
        "url": current_url,
        "date": upload_date,
        "priority": 0,
    }
    existing_url = provenance.get("earliest_known_url")
    existing_date = normalize_date(provenance.get("earliest_known_date"))
    if existing_date and _same_url(existing_url, current_url):
        current["date"] = min(
            date for date in (current["date"], existing_date) if date
        )
    dated = [current] if current["date"] else []
    for match in matches:
        if match.get("date"):
            dated.append({**match, "priority": 1})
    if not dated:
        if not any(match.get("source") not in generated_sources for match in matches):
            provenance["provenance_status"] = "unknown"
            provenance["previous_context_summary"] = None
        return

    earliest = min(
        dated,
        key=lambda item: (
            item["date"],
            item.get("priority", 1),
            item.get("url") or "",
        ),
    )
    provenance["earliest_known_url"] = earliest.get("url")
    provenance["earliest_known_date"] = earliest["date"]
    online_dates = [earliest["date"]]
    if _same_url(existing_url, current_url) or any(
        _same_url(match.get("url"), existing_url)
        and match.get("source") not in generated_sources
        for match in matches
    ):
        online_dates.append(
            normalize_date(verification["date"].get("earliest_online_date"))
        )
    verification["date"]["earliest_online_date"] = min(
        date for date in online_dates if date
    )

    earliest_url = earliest.get("url")
    page = page_by_url.get(earliest_url)
    if _same_url(earliest_url, current_url):
        provenance["provenance_status"] = (
            "earlier version found"
            if upload_date and earliest["date"] < upload_date
            else "unknown"
        )
        provenance["previous_context_summary"] = None
        if provenance["provenance_status"] == "earlier version found":
            add_field_evidence(
                extra,
                "verification.provenance.provenance_status",
                (extra.get("field_evidence") or {}).get(
                    "verification.provenance.earliest_known_date", []
                ),
            )
        return
    if not earliest_url:
        return
    if not page:
        if any(
            _same_url(match.get("url"), earliest_url)
            and match.get("source") not in generated_sources
            for match in matches
        ):
            provenance["provenance_status"] = (
                "earlier version found"
                if current["date"] and earliest["date"] < current["date"]
                else "unknown"
            )
        return

    provenance["provenance_status"] = (
        "earlier version found"
        if current["date"] and earliest["date"] < current["date"]
        else "unknown"
    )
    evidence_id = evidence_by_url.get(page.get("url")) or evidence_by_url.get(earliest_url)
    evidence_ids = [evidence_id] if evidence_id else []
    for field in (
        "verification.provenance.provenance_status",
        "verification.provenance.earliest_known_url",
        "verification.provenance.earliest_known_date",
        "verification.date.earliest_online_date",
    ):
        add_field_evidence(extra, field, evidence_ids)

    motivation = verification["motivation"]
    title = page.get("title")
    description = page.get("description") or page.get("context_excerpt")
    context = " — ".join(value for value in (title, description) if value)
    if context and previous_context_is_useful(
        context,
        motivation.get("claimed_framing"),
        context,
    ):
        provenance["previous_context_summary"] = context[:800]
        add_field_evidence(
            extra,
            "verification.provenance.previous_context_summary",
            evidence_ids,
        )
    if title:
        motivation["original_caption"] = title
        add_field_evidence(extra, "verification.motivation.original_caption", evidence_ids)
    if description:
        motivation["original_description"] = description
        add_field_evidence(extra, "verification.motivation.original_description", evidence_ids)

    source_name = page.get("author") or page.get("site_name")
    if source_name:
        verification["source"]["original_source_name"] = source_name
        add_field_evidence(extra, "verification.source.original_source_name", evidence_ids)
